sudo: true
dist: xenial
services:
  - docker
language: python
python:
  - '3.7'
before_install:
  - pip install 'lander>=0.1.0,<0.2'
  - pip install pyyaml    # for db2authors.py
script:
  # Pre-build authors.tex using the Travis CI Python
  - make authors.tex
  # Compile PDF using containerized lsst-texmf
  - docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh
    -c 'make'
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - lander --upload --pdf DMTN-140.pdf --lsstdoc DMTN-140.tex --env=travis --ltd-product
    dmtn-140
env:
  global:
    -
      # LTD_AWS_ID
      secure: RG5lbls5YKmSldSr1ibeYltqvjmJ0rjGa2o8BsViikxb9pJ81jLctjmr3eRqP0hjDHZcC+g+hxoMkPCHx8mjNREMe5sLaXMet/kuZadDJyWds/B6tNSrOXs1pJ8oSL7hSvKDCwG6czpI7g45aJhb1TEaa6yTyzPEliNJ1U3r73qe2yjPf8b7cwCVMCwEWWb6Lvp/fsbGt78XwDwz6eUje/aTMkAPwTGRDdmknIiPz2yXsbcxcHRbG2GEeAMCovzUdkLY5Yt1EDkHtskIiLa+ObISUHxS7eDm2ZybYBKrY/I7HmG7mUhDODQf5oIG2wb2JcN0c1zqY8iD/wpOB6Tc2fjHeXcSTZy8fybGKfk4iMuvG2UA8UDaqYwsZumGXCku9tpmE3XMCfOXGiiKomp29kQvgCRr3qdqNmib377AapYBtd4z6vW4mq6JU0uD4TiEBB5s7i2y/b3HCCY/rkk+0s3KMW6FvfWdoeZQNBtSYsZb4j8CiYsA/XpuisVbPGSpsfRmpvl6dqrTGuszj1RbH+XwDcr11TJ2m53w8oqQ03Cy68go47KmnO46YOdmAzpGcYvmFz9vv3gPPLFXYyVTyBaLd5R1Ytf8FHLTHzsEs2jTydSp1S2HLGkM2ckhimSTAPnHXNXjONLay5ev0hd8R0HdD+YupKPK3jL6MPOtl/A=
    -
      # LTD_AWS_SECRET
      secure: pqvJjKHITvTA8KBqn+S/i3tjyDHw4wyoWTefYKj4mtme0Mjls0Mbg/OEcSh2WCjRpboFWYUvgrLY3x1M4SColWfP4Lcxv7tJ8RaewoMd8KKb5PQ659A5AAsPQIN1cB6p4z51tCdUaYZ5HSdBIW6uDUh7hQ/+BEJn2fdRvSlEtTTXMlCEbPbjEVPfsVboME883qBxnalNsNHS3LeV8WciAX5ZS0BO3mHzMtjgpXXT1RzyGoYHnhAayMjWAsweuLCoAgN/Apkwdgy9OpPdB3/k4al8WYPCdYqerNUaGFrg+TRgtiZibUvaAYPTF8k/npjVHh8KF1h10I/qiYtrnTm7nQmPaKjvjrxUN1E8AteKVY+TkOj8fvS2GhNba0FumG6xssI6PkECvbueUi+YS3oXMfu2O5WhYcY5ZScD9aUYuF545rn4haynKbYzOKy2CjccE03RZ4Rgb+Vu83jXj7tfuS1HMSHx4YZKuyHrOaJJN68RBB9roOvDauieCWb/789uBnGD9ORYpooJ4iE1U4DJtcTzIVGpE401h1+xp+sQSGqJUOsJoqlTgRy58Z8r2qx60q9GPjTnKJfbofg2BEQ8Yo2spTkGHKV0mtEB4uTW0Uo5d08YEREGh6hjI47Sf06Oek7M5ZZjdRFpVzcJmYW3Zre8zUL+xnDfW0uDySjNmpI=
    -
      # LTD_KEEPER_USERNAME
      secure: YG7QS4nPExV/D8r5FBLmv8BC/rGQeH6qGOEea59YGSgyHiFWOLgp/bojwwlTn9gt+5Vk2ebifHODRGSxvEYil5iEdQnepjalIKpN2ERlSnhMuKyvvloBCa8M8Hc56M3Iy0plDuwSA1juHccoNJ3wEopkx6sZkWQhSjnBjBwiM38MKPRx5R+q8jZnFXjELRxK+7ffnEcnTuJbVgF/+40yIb1Nl2yQCOVAAKXoZq2JllTTSqzpFXnJbBKhzt35N9ogNlnMZTc3FYmc4t6Z+lHhnaTBu8Si7viC4KGYsA8VGmqRn/XuLJx/YA26EwKpmJAqTaIi6K+Ns2kXH6FBMsXfQOasdM34iZWvWy9KPxtOX49uWuV36TkJNEZO8vBR2kbJc2lONVgBaiqigGayIHEI7oy9FDEBem6RoB8atY/mLOKez93aCESDk2XFje8iQEK8hYeWgA5ZHxo6Q5g9F9iJJWUyLpbF2QtYM5XBFOzh+2j8ezHPuLqfD9jJxMkQd1Tt8LqH68ZMZUTRgJMC9InUQ7swV9tslrNQQ9/Be4OsvcnH2dnlTHnNMzqakJn5/X5huudi1UA3M/JfedFB/eTpYyNjyg/lwQXlyq2f/W1GcMpTAvNX4RxS2o1WZFp4KQuTAw7XiSk7CNjWiOGYQqfX49uoBdjCeBsti0DfjQlh4GQ=
    -
      # LTD_KEEPER_PASSWORD
      secure: N+8A+ihVsU9sTlLVwBy3L6R/6Eo7hg9iC6UwJBPQFRTvif0SAQ6EjlWPyrOdtCQ/4qJOCT+udBPDs+FenCLhVlt5TLw3QvV2FjE+7lyJmFhoukDI4OEZ2rBvqVDVn+QzWqsI2n5MyNZvlBzrAflr+tlIOg92/WqENegXgW3XDczlm3CVtGFulHN1bVH2aWz6vSVK0vBTN1LaALYJOor2ca02aHlUUo7Ydv9z0w0Yd+4aX++X75KTmQOGdF9Xs9+4fh+/T/kV9r7I5H8zxTNrTkkMhCzmcsypDt0JppWqEUuC16lW90HnaFPQRYZ7rN7wS4zVv7qengphYpWFcOoI/sUbnE6YxvY1E9+rcvAQ/rW9IUNsxtkheDiNy3T9urQbsqOCX4v+uPDdFT63foU8NTN+5Smz4G03S30x1tA2XZc92WWpw0yp73Big7WRKhjromLGRHyPB1vPO7mND476A0ZHqFHxcXgXrhk7ZqL0Bg8gf6dsgjaMceSforG0uEpzHRnFTgdCzm5mYGHbq8Fs3IPAEz8tDpk5SrE4wE/rvJr+Km7w5SwyzZJH3Trcix4Il0qva4eOfIE/2w8T1oKqd7PNcK9mTyISzKuU55q8SWIRoLkUGTM7jwjtOse9e4kk8rrTMKJBDzUsv5U0Pv+3h8Wnzk4ZCORUzKs9LhKiO3Y=
    -
      # LTD_KEEPER_URL
      secure: dt9w7rcctTFRqKcKX/qxefE2klSvxv2yzPwlILHxBBK01ac9E9hp2P1/UyXgg2VRX7LL56CBGrvGVcy1w5XBUNzaJDZ+6ohHImB2v6CwG1duW6w2I606kmBqurfsRE4/4G+gsAmr1t4LMhjtNz5aKLuftwN4e+Txru2AieQUvqUwGABzLbyM25kZrbyezqvzyQkIpapTUI8AtwBpsQRekN1BsOkJ6fYR7hZFsU8BQNldjlZx/EKWBVkzmfLiS64Yt+9qsovJoN5gmifkAqHsz2WhL1e1pQoANukcM8OHsIGEEWV98QDTZmlEQGFCrI29uPwv2fA2vQ4240nx+MEwOGY/TbGi8XOnGt+oU3wDEI4CDZs/LDPFXZA+wRt4Xj8/sIiw/kPKAc6Mes6zKqGQNmV5alSTY18Itqids4mDNSbOwCYo2dSXRQRdO1plm+OoS67erxZmWMWqFYoBryUea1zWksOrom3fS68BNpcbokOvSPeonzJV+vu31SYoRF33tgV2lw6jD4XcKJWgjr5i6mClwzHQuAI6euSMv+Otjy71bJruvH0M+nSvW7eMlZrCiVrq1n391MI3AU4djgzNB/rgBom1+PTrQzce1OXwUOM0C4wr/PVLjJOsCWghzFdCTXaD66hQbHq1iSXnCnKA73jny16PrJ17dNW1orwvmM4=
